language: node_js
nodejs:
- '8'
addons:
  apt:
    packages:
    - jq
env:
  global:
  - DIAG_HOST=https://demo.diag.ai
  - secure: hvQ7xIByNF6znH4QtwQXkCPf2aiiCr1UiLkWJaoAA/EzxjcWLyuMsd6pCGUqeZQol37L9f2oIN4wYtcGV0EGd5KrCFtqZaBfDTApQVLxfNLQLeQzL2MU+FWkFazL76RoNMTap3/GmhvvsI+tDIY+qOtYyk1/V5zzftlcLF8rQ+bDUDelyTjcOGW/CGRnJxEkh+8SWzmGqN+wRcGldhBHUcSjpUUlBq/RfJezQK+gxwG8JnQRmD1ZSH+WLuonjvorQEm4uV4y72oKBBsN585oXkcRpQukwNz8hESTT9SHlBHCzmbef3L0s2f7c2MOoantjmPwd2tMXpitvx92kZazxcmfpCpJ+37tHj3/QgxJ/GM4HYht35KFy8pXNuqLKW40n6amdZDlwREU3giub1Avmoi5JMdVzj+5wkzlSJvoNGdqmvvFexZrjRcwIKsloUceFP24HwIqSm5IaIN9yTqgdIUYHlzKaEGMT5XKkf7GKL6oj6oR87jT4juznaGzJD9pkDhTg4cfMDASNcx5xWcbKm2WgfKpDB2iViXtnTBsv2NtDe+Of+QnO8j2b6tgCBvg0rpFM7oNPsbKGeeP8YEy/qeewWNqFrH5hT1MB+V+/VzAP3Ja10XBn/darlvnj0slXo5N2anuKvJzDHFjexYY5rb/rf7QsztmEh0BeoguRAs=
before_install:
- mkdir -p /tmp/logs
install:
- set -o pipefail && npm install -g diag@latest 2>&1 | tee /tmp/logs/diag_install.log
script:
- set -o pipefail && npm install 2>&1 | tee /tmp/logs/npm_install.log
- set -o pipefail && npm run test 2>&1 | tee /tmp/logs/test.log
- set -o pipefail && npm run build 2>&1 | tee /tmp/logs/build.log
after_failure:
- diag mkds --space cidemo--name "${TRAVIS_REPO_SLUG:-missing_repo_name} -- Build
  ${TRAVIS_BUILD_NUMBER:--1}" --desc "${TRAVIS_COMMIT_MESSAGE:-missing_commit_message}"
  -j > /tmp/dataset.json
- cat /tmp/dataset.json | jq -r '. | "d/\(.id.space_id)/\(.id.item_id)"' > /tmp/dataset_id
- diag cp /tmp/logs --name logs.zip $(cat /tmp/dataset_id)
- diag cp /home/travis/build/diag/diag-app --name source.zip --gitignore $(cat /tmp/dataset_id)
notifications:
  slack:
    secure: RkINH5QUqYPmi74RONHbDHtMZ3NsI7ONwB+54ZquK31et+izeYxiTS4XJ8Kr6SFQLouozHvbn9QB26RMIupkcVXUGhaoBhIbye/Pmw+5rTEJVXunt19jNpbXx5QpIz94/a98NcrIRxO50mOW3xaypAZnAMwIPNCKgRu2mhnGngJWjiOOd0uGFbznOixdG3wvgpzfD6ST0IBEwzK1LbZ4Lodu6M2TG3zRtRhX1ekd0XsKqHMHZmD2wrje716c6Ufu/tIBWnqTBPrlPEETlsrV1nx2ABDq2uBWoaVmUkVWlmUup1siAXUQnHPohqNpNzAGLBKL7B5il8eF5TX4CLYG/Lw5jCIO6HsBXBFqndSce8rHecnim6SmqZjzucOcu0MYP1py19WnNOOoUnMW2clwUJ8nYqasTRvXJnKOHgjRoTorX41nPCXopoKXqMenXv/Py/SnG5HFq1ETEGs1BZCTIXqbBflGlzkieINdfWapsF+KYc+JZUy4JdIjXG8ia7+4yaRVd2n9MT/U1nhCy+IHV9/BlMBC34KtjZprAXxgl8aqxIZxzzjNU3Bgj9KHvKWTWGZC/Agr2stEF5FTgQjCuAb350Id1syx6rgxJor0f/QioMJbx6ggzCOuLCFTLGcdUgeSc3e+alK0otb+g8U4aVj5q1sa72Ax43aEOXPYanY=
